### ISSUE TITLE
jobs_runs_wait_for_completion doesn't retry correctly

### ISSUE THREAD

**Issue by nchammas** [PrefectHQ/prefect-databricks#80]
# Expectation / Proposal

I may be misunderstanding something, but I have a custom flow that calls `jobs_runs_wait_for_completion` under the hood. I am calling my custom flow with additional options like this:

```python
custom_flow.with_options(retries=1)
```

However, when the underlying Databricks job fails, I see it acknowledged by Prefect but I don't see the Databricks job ever actually rerun.

Am I misunderstanding something basic about how to use `jobs_runs_wait_for_completion` in combination with `with_options(retries=)` to get automatic retries of the called Databricks job?

# Traceback / Example

```
17:37:34.392 | INFO    | Flow run 'amorphous-sawfly' - Received non-final state 'AwaitingRetry' when proposing final state 'Failed' and will attempt to run again...
17:37:36.726 | INFO    | Flow run 'encouraging-bustard' - Finished in state Completed()
17:37:36.860 | ERROR   | Flow run 'amorphous-sawfly' - Encountered exception during execution:
Traceback (most recent call last):
  File "/Users/nchammas/Library/Caches/pypoetry/virtualenvs/ozawa-prefect-LtscNPhu-py3.9/lib/python3.9/site-packages/prefect/engine.py", line 833, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "/Users/nchammas/Library/Caches/pypoetry/virtualenvs/ozawa-prefect-LtscNPhu-py3.9/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 292, in aresult
    return await asyncio.wrap_future(self.future)
  File "/Users/nchammas/Library/Caches/pypoetry/virtualenvs/ozawa-prefect-LtscNPhu-py3.9/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 316, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/nchammas/dev/spx/ozawa/prefect2/ozawa_prefect/flows/databricks/__init__.py", line 66, in run_job_or_fail
    raise Exception(
Exception: {'result_state': 'FAILED', 'run_page_url': 'https://...cloud.databricks.com/?o=xxx#job/126796463608738/run/28379095', 'notebook_output': {}, 'error': 'ArithmeticException: / by zero'}
17:37:37.000 | ERROR   | Flow run 'amorphous-sawfly' - Finished in state Failed("Flow run encountered an exception. Exception: {'result_state': 'FAILED', 'run_page_url': 'https://...cloud.databricks.com/?o=xxx#job/126796463608738/run/28379095', 'notebook_output': {}, 'error': 'ArithmeticException: / by zero'}")
```

- [x] I would like to [help contribute](https://PrefectHQ.github.io/prefect-databricks/#contributing) a pull request to resolve this!

**Comment by nchammas** [comment]
I migrated to `jobs_runs_submit_by_id_and_wait_for_completion` and don't see this issue with retries anymore, so I'm not sure what's going on. But we were perhaps misunderstanding or misusing `jobs_runs_wait_for_completion` somehow.
